include:
  - board: nice_nano_v2
    shield: corne-ish_zen_left
  - board: nice_nano_v2
    shield: corne-ish_zen_right
  - board: nice_nano_v2
    shield: reviung41
  - board: nice_nano_v2
    shield: settings_reset
